---
- hosts: localhost
  connection: local
  tasks:
  - name: Get a list of all VirtualMachines
    kubevirt.core.kubevirt_vm_info:
    register: vm_list
  
  - name: Nice YAML
    ansible.builtin.set_fact:
      nice_vm:  "{{ vm_list | to_nice_yaml }}"

  - name: Output to vmdata.yml
    ansible.builtin.template:
      src: vmdata.yml.j2
      dest: vmdata.yml

  - name: Output to vmdata.csv
    ansible.builtin.template:
      src: vmdata.csv.j2
      dest: vmdata.csv

